# Generated by Django 5.2.3 on 2025-06-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawGPSData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed_kmh", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("road_id", models.BigIntegerField()),
                ("latitude_start", models.FloatField()),
                ("longitude_start", models.FloatField()),
                ("latitude_end", models.FloatField()),
                ("longitude_end", models.FloatField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("speed_kmh", models.FloatField()),
                ("congestion_level", models.CharField(max_length=20)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["road_id", "time"],
                        name="routes_traf_road_id_3993fe_idx",
                    )
                ],
            },
        ),
    ]
